
set a = createobject("wscript.shell")

mytxt1=inputbox("Coloque a primeira mensagem aqui","CAIO NA VILA O PEIXE FUZILA")
mytxt2=inputbox("Coloque a segunda mensagem aqui","CAIO NA VILA DENOVO O PEIXO BOTA FOGO")
mytxt3=inputbox("Coloque a terceira mensagem aqui","CAIO NA VILA PELA TERCEIRA VEZ O PEIXE COME SUA EX")
mytxt4=inputbox("Coloque a quarta mensagem aqui","CAIU NA VILA PELA DENOVO O PEIXE COME SEU BUTAO ")
mytxt5=inputbox("Coloque a quinta mensagem aqui","Type some text 5","hahahahahaha")
mytxt6=inputbox("Coloque a sexta mensagem aqui","Type some text 6","Yo i be back")
mytxt7=inputbox("Coloque a setima mensagem aqui","Type some text 7","Bdw i love your stream")
mytxt8=inputbox("Coloque a oitava mensagem aqui","Type some text 8","Keep it up my guy!")
mytxt9=inputbox("Coloque a nona mensagem aqui","Type some text 9","You Trippin hard dude")
mytxt10=inputbox("Coloque a decima mensagem aqui","Type some text 10","Am I Weird lol?")
mynum=inputbox("quantas vezes vai repetir o texto ?","spamnumber","20") 
myspeed=inputbox("a cada quantos milisegundos vai enviar o spam! 1000=1sec.","delay","9000") 
mywait=inputbox("Qual tempo o script vai esperar para ativar","Wait?","3")

msgbox("You have " & mywait & " secs to put focus on your target text area!")
wscript.sleep (mywait*1000) 
for i=1 to mynum 		
	a.sendkeys (mytxt1)       
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)
	a.sendkeys (mytxt2)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt3)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt4)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt5)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt6)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt7)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt8)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt9)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt10)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
next
strlol = ("- Spam Bot by: Trajano // Ataque Acabado! - ")
	a.sendkeys (strlol)   
	a.sendkeys ("{ENTER}")
msgbox("Flood Acabado!")
